load("//build/kernel/kleaf:kernel.bzl", "ddk_headers", "ddk_uapi_headers")

package(
    default_visibility = [
        "//visibility:public"],
)

filegroup(
    name = "_video_uapi_headers",
    srcs = glob([
        "include/uapi/vidc/media/*.h",
    ]),
)

ddk_headers(
    name = "uapi_headers",
    hdrs = [
        ":_video_uapi_headers",
    ],
    includes = ["include/uapi/vidc"],
)

ddk_headers(
    name = "blair_headers",
    hdrs = glob([
      "driver/platform/blair/inc/*.h",
    ]),
    includes = ["driver/platform/blair/inc"]
)

ddk_headers(
    name = "pitti_headers",
    hdrs = glob([
      "driver/platform/blair/inc/*.h",
    ]),
    includes = ["driver/platform/blair/inc"]
)

ddk_headers(
    name = "ar50lt_headers",
    hdrs = glob([
      "driver/variant/ar50lt/inc/*.h",
    ]),
    includes = ["driver/variant/ar50lt/inc"]
)

ddk_headers(
    name = "neo-la_headers",
    hdrs = glob([
      "driver/platform/neo/inc/*.h",
    ]),
    includes = ["driver/platform/neo/inc"]
)

ddk_headers(
    name = "iris2_headers",
    hdrs = glob([
      "driver/variant/iris2/inc/*.h",
    ]),
    includes = ["driver/variant/iris2/inc"]
)

ddk_headers(
    name = "vidc_headers",
    hdrs = glob([
      "driver/vidc/inc/*.h",
      "driver/variant/common/inc/*.h",
      "driver/platform/common/inc/*.h"
    ]),
    includes = ["driver/vidc/inc", "driver/platform/common/inc"]
)

ddk_headers(
    name = "video_driver_headers",
    hdrs = [":uapi_headers", "blair_headers", "ar50lt_headers", "neo-la_headers", "iris2_headers", "vidc_headers"]
)

ddk_uapi_headers(
    name = "msm_video_ddk_uapi_headers",
    srcs = [
        ":_video_uapi_headers",
    ],
    out = "video-uapi-headers.tar.gz",
    kernel_build = "//:target_kernel_build",
)

load(":target.bzl", "define_blair")
define_blair()

load(":target.bzl", "define_pitti")
define_pitti()

load(":target.bzl", "define_neo-la")
define_neo-la()
